require 'opengl'
require 'glu'
require 'gosu'
require './Key'
require './InputKey'
require './Input'
require './Color'
require './Font'
require './Text'
require './Sprite'
require './Sound'
require './Music'
require './GameWindow'
require './GameMapObject'
require './GameMapGround'
require './GameMapMovableObject'
require './GameMapEvent'
require './GameMapPlayer'
require './GameScene'
require './GameScene3D'
require './GameMessageScene'
require './GameMapScene'
require './GameMenuScene'
require './GameBattleScene'
require './StartingCreditsScene'
require './TitleScreenScene'
require './LoadingScreenScene'
require './MapTest'

$gameWindow = GameWindow.new("PGM",940,528)
$gameWindow.currentGameScene = MapTest.new("Carte de test",0,64,32,0)
#$gameWindow.currentGameScene = StartingCreditsScene.new
$gameWindow.show
